env:
  browser: true
  es6: true
  mocha: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
"parser": "babel-eslint"
rules: {
  'guard-for-in': 0,
  'jsx-a11y/label-has-associated-control': 'off',
  'lines-between-class-members': ["error", "always", { exceptAfterSingleLine: true }]
}
"overrides": [
  {
    "files": [
      "**/*.spec.js",
      "**/*.spec.jsx"
    ],
    "env": {
      "jest": true
    }
  }
]
